export const Locations = [
    {
      name: 'Kathmandu University',
      address: '28 Kilo, Banepa, Kavre',
      latitude: 27.6187,
      longitude: 85.5384,
    },
    {
      name: 'Tribhuvan University',
      address: 'Kirtipur, Kathmandu',
      latitude: 27.6818,
      longitude: 85.2883,
    },
    {
      name: 'Patan Durbar Square',
      address: 'Patan, Lalitpur',
      latitude: 27.6726,
      longitude: 85.3257,
    },
    {
      name: 'Boudhanath Stupa',
      address: 'Boudha, Kathmandu',
      latitude: 27.7215,
      longitude: 85.3620,
    },
    // Add more suggested locations here
    {
      name: 'Swayambhunath Stupa',
      address: 'Swayambhu, Kathmandu',
      latitude: 27.7149,
      longitude: 85.2904,
    },
    {
      name: 'Pashupatinath Temple',
      address: 'Pashupati Nath Road, Kathmandu',
      latitude: 27.7106,
      longitude: 85.3487,
    },
    {
        name: 'Kathmandu Durbar Square',
        address: 'Basantapur, Kathmandu',
        latitude: 27.7043,
        longitude: 85.3076,
      },
      {
        name: 'Pashupatinath Temple',
        address: 'Pashupati, Kathmandu',
        latitude: 27.7104,
        longitude: 85.3481,
      },
      {
        name: 'Swayambhunath Stupa',
        address: 'Swayambhu, Kathmandu',
        latitude: 27.7149,
        longitude: 85.2900,
      },
      {
        name: 'Boudhanath Stupa',
        address: 'Boudha, Kathmandu',
        latitude: 27.7215,
        longitude: 85.3621,
      },
      {
        name: 'Patan Durbar Square',
        address: 'Mangal Bazaar, Patan',
        latitude: 27.6725,
        longitude: 85.3256,
      },
      {
        name: 'Bhaktapur Durbar Square',
        address: 'Bhaktapur',
        latitude: 27.6710,
        longitude: 85.4298,
      },
      {
        name: 'Changu Narayan Temple',
        address: 'Changunarayan, Bhaktapur',
        latitude: 27.7105,
        longitude: 85.4277,
      },
      {
        name: 'Thamel',
        address: 'Thamel, Kathmandu',
        latitude: 27.7156,
        longitude: 85.3123,
      },
      {
        name: 'Garden of Dreams',
        address: 'Kaiser Mahal, Kathmandu',
        latitude: 27.7137,
        longitude: 85.3153,
      },
      {
        name: 'Lalitpur Engineering College',
        address: 'Chakupat, Lalitpur',
        latitude: 27.6688,
        longitude: 85.3245,
      },
      {
        name: 'Tribhuvan University',
        address: 'Kirtipur, Kathmandu',
        latitude: 27.6785,
        longitude: 85.2771,
      },
      {
        name: 'National Museum of Nepal',
        address: 'Chhauni, Kathmandu',
        latitude: 27.7076,
        longitude: 85.2902,
      },
      {
        name: 'Patan Museum',
        address: 'Patan Durbar Square, Lalitpur',
        latitude: 27.6735,
        longitude: 85.3248,
      },
      {
        name: 'Bhaktapur Pottery Square',
        address: 'Bhaktapur',
        latitude: 27.6720,
        longitude: 85.4267,
      },
      {
        name: 'Nagarkot',
        address: 'Nagarkot, Bhaktapur',
        latitude: 27.7104,
        longitude: 85.5216,
      },
      {
        name: 'Kopan Monastery',
        address: 'Kopan, Kathmandu',
        latitude: 27.7428,
        longitude: 85.3482,
      },
      {
        name: 'Hanuman Dhoka',
        address: 'Basantapur, Kathmandu',
        latitude: 27.7046,
        longitude: 85.3073,
      },
      {
        name: 'White Monastery (Seto Gumba)',
        address: 'Ramkot, Kathmandu',
        latitude: 27.6931,
        longitude: 85.2556,
      },
      {
        name: 'Dakshinkali Temple',
        address: 'Pharping, Kathmandu',
        latitude: 27.6174,
        longitude: 85.2717,
      },
      {
        name: 'Phulchowki Hill',
        address: 'Lalitpur',
        latitude: 27.5772,
        longitude: 85.3832,
      },
      {
        name: 'Godavari Botanical Garden',
        address: 'Godavari, Lalitpur',
        latitude: 27.5919,
        longitude: 85.3835,
      },
      {
        name: 'Prime Boys Hostel',
        address: 'Baneshwor, Kathmandu',
        latitude: 27.69598249553103,
        longitude: 85.34400859084381,
      },
  ];